name: tenflrpay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.6.9
  barcode_scan: ^3.0.1
  bot_toast: ^3.0.5
  chopper: ^3.0.6
  cloud_firestore: ^0.12.2
  cupertino_icons: ^1.0.0
  currency_text_input_formatter: ^0.3.1
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  device_info: ^0.4.2+9
  devicelocale: ^0.3.3
  dio: ^3.0.10
  encrypt: ^4.1.0
  expandable: ^4.1.4
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_crashlytics: ^0.1.4+1
  firebase_messaging: ^6.0.16
  firebase_performance: ^0.3.0
  firebase_remote_config: ^0.3.1+1
  flare_flutter: ^2.0.6
  flt_telephony_info: ^0.1.3
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.6
  flutter_hooks: ^0.14.1
  flutter_masked_text: ^0.8.0
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.1
  font_awesome_flutter: ^8.10.0
  get_it: ^5.0.1
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.3
  i18n_extension: ^1.4.5
  injectable: ^1.0.5
  intl: ^0.16.0
  intl_phone_number_input: ^0.5.2+2
  intro_slider: ^2.3.3
  json_annotation: ^3.1.0
  kt_dart: ^0.8.0
  local_auth: ^0.6.3
  math_expressions: ^2.0.1
  ntp: ^1.0.7
  package_info: ^0.4.3
  path_provider: ^1.6.22
  pie_chart: ^4.0.1
  pin_entry_text_field: ^0.1.4
  pinput: ^0.2.5
  provider: ^4.3.2+2
  qr_flutter: ^3.2.0
  rflutter_alert: ^1.1.0
  rxdart: ^0.24.1
  settings_ui: ^0.4.0
  shared_preferences: ^0.5.12+2
  smooth_page_indicator: ^0.2.0
  trust_fall: ^1.0.4
  url_launcher: ^5.7.1
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  chopper_generator: ^3.0.5
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.4.1
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/navbar_icons/
    - assets/svg/
    - assets/flare/

  fonts:
    # TenflrIcons
    - family: TfIcons
      fonts:
        - asset: assets/icons/TfIcons.ttf

    # Fonts
    - family: BrushScript
      fonts:
        - asset: assets/fonts/BrushScript.ttf
    - family: appleSymbols
      fonts:
        - asset: assets/fonts/appleSymbols.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Helvetica-Oblique.ttf
          style: italic
        - asset: assets/fonts/helvetica-light.ttf
          weight: 300
